---
title: "Millisecond plots"
author: "Pedro J. Aphalo"
date: "`r Sys.Date()`"
output: html_document
---

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, UVBf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, UVAf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, UVA1f_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, Bluef_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:35") & TIMESTAMP < ymd_hm("2024-08-09 13:40")), aes(TIMESTAMP, Greenf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, UVBf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, UVAf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, UVA1f_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)
```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, Bluef_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)
```

```{r, eval=FALSE}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 13:05") & TIMESTAMP < ymd_hm("2024-08-09 13:10")), aes(TIMESTAMP, Greenf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)
```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, UVBf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, UVAf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, UVA1f_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, Bluef_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:35") & TIMESTAMP < ymd_hm("2024-08-09 12:40")), aes(TIMESTAMP, Greenf_Den)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```
## Plot recent

```{r}
n_hours <- 25/60 # hours of data
n_rows <- n_hours * 60 * 60 * 20 / 3 # 20 readings per second, during four times 5 min per hour

theme_set(theme_minimal())
```


```{r}
# ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:05") & TIMESTAMP < ymd_hm("2024-08-09 15:40")),
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, PAR_Den_CS)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```

```{r}
# ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:05") & TIMESTAMP < ymd_hm("2024-08-09 15:40")),
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, UVBf_Den)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```


```{r}
# ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-08-09 12:05") & TIMESTAMP < ymd_hm("2024-08-09 15:40"))
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, UVAf_Den)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```


```{r}
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, UVA1f_Den)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```


```{r}
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, Bluef_Den)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```


```{r}
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, UVBf_Den / UVA1f_Den)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "top") +
  expand_limits(y = 0)

```

```{r}
ggplot(tail(millisecond.tb, n_rows), aes(TIMESTAMP, PAR_Den_CS)) +
#  geom_line() +
  geom_point(size = 0.1, alpha = 1/10) +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 7:00") & TIMESTAMP < ymd_hm("2024-06-07 7:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)
```
`

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 8:00") & TIMESTAMP < ymd_hm("2024-06-07 8:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 9:00") & TIMESTAMP < ymd_hm("2024-06-07 9:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 10:00") & TIMESTAMP < ymd_hm("2024-06-07 10:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 11:00") & TIMESTAMP < ymd_hm("2024-06-07 11:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 12:00") & TIMESTAMP < ymd_hm("2024-06-07 12:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 13:00") & TIMESTAMP < ymd_hm("2024-06-07 13:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 14:00") & TIMESTAMP < ymd_hm("2024-06-07 14:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 15:00") & TIMESTAMP < ymd_hm("2024-06-07 15:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 16:00") & TIMESTAMP < ymd_hm("2024-06-07 16:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 17:00") & TIMESTAMP < ymd_hm("2024-06-07 17:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 19:00") & TIMESTAMP < ymd_hm("2024-06-07 19:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  expand_limits(y = 0)

```


```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hm("2024-06-07 18:00") & TIMESTAMP < ymd_hm("2024-06-07 18:15")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)

```

```{r}
ggplot(subset(millisecond.tb[-1, ], TIMESTAMP > ymd_hms("2024-05-10 15:03:30") & TIMESTAMP < ymd_hms("2024-05-10 15:03:45")), aes(TIMESTAMP, PAR_Den_CS)) +
  geom_line() +
  stat_panel_counts(label.y = "bottom") +
  expand_limits(y = 0)
```
